longhorn:
  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1
    reclaimPolicy: Retain
    defaultFsType: ext4

  defaultSettings:
    defaultReplicaCount: 1
    replicaAutoBalance: best-effort
    storageOverProvisioningPercentage: 100
    storageMinimalAvailablePercentage: 15
    defaultDataPath: /var/lib/longhorn
    createDefaultDiskLabeledNodes: false
    orphanAutoDeletion: true

  ingress:
    enabled: false