---
# LoadBalancer Adresse für die k3s API.
lb_ip: 192.168.122.10
api_port: 6443

# NodePorts des späteren Traefik Ingress Controllers.
# HAProxy leitet Port 80 und 443 auf diese NodePorts der Agent Nodes weiter.
# Diese Werte müssen später zur Traefik Helm Installation passen.
traefik_http_port: 30080
traefik_https_port: 30443

# Optionaler Token über ENV Variable.
# Aktuell erzeugt das Playbook selbst einen lokalen Bootstrap Token.
# Dieser Wert bleibt für spätere Erweiterungen erhalten.
k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('', true) }}"

# Eingebautes K3s Traefik wird deaktiviert.
# Traefik soll später selbst per Helm installiert werden.
disable_traefik: true

# Server Nodes sollen keine normalen Workloads tragen.
taint_servers: true