---
lb_ip: 192.168.178.50
api_port: 6443

traefik_http_port: 30080
traefik_https_port: 30443

k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('', true) }}"

disable_traefik: true
taint_servers: true